[phases.setup]
nixPkgs = [
  'nodejs-18_x',
  'chromium',
  'glib',
  'nss',
  'nspr',
  'atk',
  'at-spi2-atk',
  'at-spi2-core',
  'cups',
  'dbus',
  'gtk3',
  'libdrm',
  'xorg.libX11',
  'xorg.libXcomposite',
  'xorg.libXdamage',
  'xorg.libXext',
  'xorg.libXfixes',
  'xorg.libXrandr',
  'xorg.libxcb',
  'mesa',
  'alsa-lib'
]

[phases.install]
cmds = ['npm ci']

[start]
cmd = 'node server.js'
