[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"

[build.nixpacksPlan.phases.setup]
nixPkgs = [
  "nodejs_18",
  "glib",
  "nspr",
  "nss",
  "dbus",
  "expat",
  "at-spi2-core",
  "gtk3",
  "atk",
  "at-spi2-atk",
  "cairo",
  "pango",
  "libxkbcommon",
  "libX11",
  "libXcomposite",
  "libXdamage",
  "libXext",
  "libXfixes",
  "libXrandr",
  "libxcb",
  "alsaLib",
  "mesa",
  "gbm"
]

[build.nixpacksPlan.phases.install]
cmds = ["npm ci"]

[build.nixpacksPlan.start]
cmd = "node server.js"
