[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_18"]

[build.nixpacksPlan.phases.install]
cmds = ["npm ci"]

[build.nixpacksPlan.start]
cmd = "node server.js"
